language: python
python:
  - "2.7"
# install dependencies
install: "pip install -r requirements.txt"
# run tests and pep8 check
script:
  - nosetests
  - pep8 ScratchInoConvertor
git:
    submodules: false
